### PR TITLE
Add IT translation

### PR DESCRIPTION
**Pull request by deframet**
Added italian messages.json and storedesc.txt

### CODE REVIEW

**Comment by bilde2910** [comment]
Hi @deframet, and thank you for offering a translation to Italian! Before we merge this into the code base, I have just a couple of questions about some specific sentences that caught my eye when reading through it.

> Questa estensione è sviluppata da bilde2910, un semplice membro della **community** di modding.

Should the word "community" above be translated into any Italian equivalent?

> Se sei uno di questi e vuoi togliere il tuo sito dalla lista, ti suggerisco di parlare con le persone del canale #stopmodrepostsl **su** EsperNet, valuteranno se è una buona idea toglierti dalla lista.
**0**

I will assume that the l at the end of #stopmodreposts is just a typo, so I will remove that. However, I stopped and thinked about "su" for a little while. From what I can gather, su means "over" or "on top of" or "above" or a similar equivalent. The channel is not above the EsperNet network, it's part of the network - you might consider it to be "in" EsperNet. Would "di" be a better substitute than "su" in this context?

I will also remove the zero at the end of the file, but I must say I am really curious as to how it got there..

There are also a couple of typos in the messages.json file and one or two in storedesc.txt, but I can fix those myself. It would be nice if you could let me know here what to do about the concerns above so I can fix them for you, or, if you want to, change the files yourself and add them to this pull request.

Kind regards,
bilde2910

**Comment by deframet** [comment]
@bilde2910 Thank you for the quick reply.
1.  Community has an italian equivalent (comunità) but community is more widespread.
2.  I don't see any zeros in the commit so [WTF](https://cloud.githubusercontent.com/assets/18748569/18325389/6121c500-7541-11e6-96e5-e7860f1885a0.png)
3. **Su** has many meanings. In this case **(along with EsperNet)** it specifies that the channel **#stopmodrepostsl** is in the **EsperNet** network. It's not wrong.

**Comment by bilde2910** [comment]
Thank you for responding that quickly! I will merge the pull request and fix the typos that I found. Strangely, when I look at the commit now, I cannot see the zero anymore. I could swear it was there! Maybe GitHub just freaked out for a bit; I don't know. It's gone now.

**Comment by bilde2910** [comment]
The things I changed were "signbifica" -> "significa" and "sconsigniato" -> "sconsigliato". Please let me know if these should be changed back.

**Comment by deframet** [comment]
*  Yes, you can change them, they are typos. 
*  If you want you can mention my GitHub account but you are not constrained to do so.

**Comment by bilde2910** [comment]
Thank you for your quick response. And thank you again for your translation! This will undoubtedly help Italian speakers. The changes have been pushed to the Chrome and Opera web stores, the former should go live within an hour and the latter within a day or so. As for Firefox... let's just say that its i18n implementation is rather confusing, but it will be added as soon as I know that our plugin can support it.

I'll give your GitHub account a mention on Twitter!

**Comment by deframet** [comment]
If in your Twitter account you were trying to say "Do you speak italian?", it's "Parli italiano?". 
"Parla italiano?" is like saying "Does he/she speak italian?".
If you can I suggest you to modify the post. I don't have Twitter so I don't know if it's allowed ;)

**Comment by deframet** [comment]
No problem and thank you for the mention :)

**Pull request merged**
