### PR TITLE
License

### LINKED ISSUE #7: Licence
What kind of licence should we use?

I suggest something that allows for redistribution as long as a link is provided to our website.

### PR DESCRIPTION
**Pull request by coolsquid**
@VictiniX888, @bilde2910, I need your permission. The other contributors additions are no longer in the repository, so their permissions are not required. Closes #7.

### CODE REVIEW

**Comment by bilde2910** [comment]
Creative Commons is perfectly fine with me :)

**Comment by coolsquid** [comment]
I was thinking of making a CLA too, but I need Victini to do that.

**Comment by VictiniX888** [comment]
I'm fine with Creative Commons too.
CLA though, I'll think about it, but is it really necessary?

**Comment by coolsquid** [comment]
Only if many people contributes.

**Pull request merged**
