### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by rchard2scout**

### CODE REVIEW

**Comment by bilde2910** [comment]
Hi @rchard2scout,

First of all, thank you very much for your contribution to the campaign! We value translations particularly much because they make the plugins accessible to many more people in their native language. That said, your translation looks very good and definitely appears to be honestly produced, so I've included it in the plugins. I'll get to work updating them with your translation as soon as possible after I figure out how to submit to Firefox, seeing as it's been a while since I've done that.

Would you mind if I thanked you for this contribution on Twitter? If so, are you on Twitter yourself, or can I mention your GitHub username?

Thank you again!

**Comment by bilde2910** [comment]
The translation has been uploaded to Chrome Web Store and Opera add-ons and should appear on both within at most a day. Firefox somehow doesn't support translations yet, so I'll look more into that.

**Comment by rchard2scout** [comment]
Hi @bilde2910, thanks for your fast response, and thanks for including it!
Thanking me is fine, my twitter username is the same as here on github, @rchard2scout.

**Comment by bilde2910** [comment]
You're very welcome :) I've posted a Tweet about it. Thanks again for your contribution!

**Pull request merged**
